services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    ports:
      - "8080:8080"
    command:
      - start-dev
    depends_on:
      - db

  db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data



volumes:
  postgresql:
